#!/bin/bash
SUCCESS=0
FAILURE=1

#
# This script initializes application configuration data for the release
#
if [[ -z "$SERVICE_ENDPOINT_PRODUCT_DETAILS" ]]; then
  echo "Environment variable SERVICE_ENDPOINT_PRODUCT_DETAILS is not defined."; exit $FAILURE
else
  echo product_details="$SERVICE_ENDPOINT_PRODUCT_DETAILS" > target/classes/endpoints.properties
fi

exit $SUCCESS