#!/bin/bash
SUCCESS=0
FAILURE=1
#
# This script performs a simple functional test agaist the locally deployed application
#
result=$(curl -s http://localhost:80/)

if [[ "$result" =~ "Product Catalog" ]]; then
    echo 'Functional tests passed.'; exit $SUCCESS
else
    echo 'Functional tests failed.'; exit $FAILURE
fi