#!/bin/bash
SUCCESS=0
FAILURE=1
ERROR=`tput setaf 1`
INFO=`tput setaf 7`
#
# This script performs a simple functional test agaist the locally deployed application
#
main_page=$(curl -s http://localhost:$1/prodcatalog/)
prod_details=$(curl -s http://localhost:$1/prodcatalog/product?id=202)

if [[ "$main_page" =~ "Product Catalog" && "$prod_details" =~ "Product Details" ]]; then
    echo "${INFO}Functional tests passed."; exit $SUCCESS
else
    echo "${ERROR}Functional tests failed for the web content: $result"
    echo $result
    exit $FAILURE
fi